; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

	TITLE	c:\Users\anuwat\documents\visual studio 2017\Projects\SystemHelloWorl\SystemHelloWorl\Math.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__F0D52EA0_math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPBDPBD@Z				; Log
PUBLIC	?Multiply@@YAHHH@Z				; Multiply
PUBLIC	__JustMyCode_Default
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File c:\users\anuwat\documents\visual studio 2017\projects\systemhelloworl\systemhelloworl\math.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __F0D52EA0_math@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _b$[ebp]
; Line 10
	pop	ebp
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Log@@YAPBDPBD@Z
_TEXT	SEGMENT
_message$ = 8						; size = 4
?Log@@YAPBDPBD@Z PROC					; Log, COMDAT
; File c:\users\anuwat\documents\visual studio 2017\projects\systemhelloworl\systemhelloworl\math.cpp
; Line 2
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __F0D52EA0_math@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR _message$[ebp]
; Line 4
	pop	ebp
	ret	0
?Log@@YAPBDPBD@Z ENDP					; Log
_TEXT	ENDS
END
