.PHONY: clean All

All:
	@echo "----------Building project:[ InitializeVars - Debug ]----------"
	@cd "InitializeVars" && "$(MAKE)" -f  "InitializeVars.mk"
clean:
	@echo "----------Cleaning project:[ InitializeVars - Debug ]----------"
	@cd "InitializeVars" && "$(MAKE)" -f  "InitializeVars.mk" clean
