.PHONY: clean All

All:
	@echo "----------Building project:[ PrimitiveTypes - Debug ]----------"
	@cd "PrimitiveTypes" && "$(MAKE)" -f  "PrimitiveTypes.mk"
clean:
	@echo "----------Cleaning project:[ PrimitiveTypes - Debug ]----------"
	@cd "PrimitiveTypes" && "$(MAKE)" -f  "PrimitiveTypes.mk" clean
